Update HTS Initial form with the revised changes
palladiumkenya/openmrs-config-kenyaemr pull request #299
Opened 2023-12-19 20:53 UTC by ErickSomie

### Description
Update the population type by adding vulnerable population
Add disability status
Update the HIV test with the 3 tier testing

2023-12-20 07:03 UTC, donaldkibet requested changes

2023-12-20 07:03 UTC, donaldkibet commented on configuration/ampathforms/HTS_Initial_Test.json
> +                  "label": "HIV Test 2 Results:",
@ErickSomie please not this should be captured as an obsGroup see [here](https://github.com/palladiumkenya/openmrs-config-kenyaemr/pull/295)

2023-12-20 14:24 UTC, Murithijoshua approved these changes

2023-12-22 05:06 UTC, makombe commented
@ErickSomie Please look into the conflicts

2023-12-22 05:26 UTC, makombe commented
Also take noted of test two result and expiry dates concepts are different from those of test one. I had aligned them #295

2024-01-02 13:13 UTC, donaldkibet commented
@ErickSomie please resolve conflicts

2024-05-09 17:04 UTC, RAJABIBRAZ commented
the form is outdated

2024-05-09 17:04 UTC, closed without merging