Update HTS_Initial_ver_no_consent_given_to_true
palladiumkenya/openmrs-config-kenyaemr pull request #330
Opened 2024-01-04 05:59 UTC by ckote

2024-01-08 04:05 UTC, donaldkibet requested changes

2024-01-08 04:05 UTC, donaldkibet commented on configuration/ampathforms/HTS_Initial_Test.json
> +                  "label": "Kit Name",
From the above we have `Kit 1 Name` `Kit 2 name` and `Kit 3 Name` notice the previous version repeated `Kit 1 Name` is this correct @makombe @mmatheka

2024-01-08 04:05 UTC, donaldkibet commented on configuration/ampathforms/HTS_Initial_Test.json
> +                "max": "",
Removing the upper bound will cause the validation not to work. Is this behaviour intended

2024-05-09 16:59 UTC, closed without merging

2024-05-09 16:59 UTC, RAJABIBRAZ commented
there is a more updated form than this