update MAT Initial form
palladiumkenya/openmrs-config-kenyaemr pull request #382
Opened 2024-02-26 20:04 UTC by mmatheka

2024-02-26 20:44 UTC, makombe requested changes

2024-02-26 20:44 UTC, makombe commented on configuration/ampathforms/MAT_Initial_Registration_Form.json
> -    }
@mmatheka Please avoid removing the metedata. When you remove this, the form will not be processe

2024-02-26 21:04 UTC, mmatheka commented on configuration/ampathforms/MAT_Initial_Registration_Form.json
> -    }
Have replaced the missing meta, You can have a look. Thanks

2024-02-28 10:05 UTC, jecihjoy approved these changes

2024-02-28 10:06 UTC, merged