OVC Enrollment Form Changes
palladiumkenya/openmrs-config-kenyaemr pull request #479
Opened 2024-04-23 05:10 UTC by ErickSomie

2024-04-23 05:29 UTC, donaldkibet commented
Thanks @ErickSomie could you provide more context on what these changes intent to achieve together with a better description of what the changes are about.

2024-04-23 05:30 UTC, donaldkibet requested changes
Thanks @ErickSomie could you provide more context on what these changes intent to achieve together with a better description of what the changes are about.

2024-05-09 16:53 UTC, RAJABIBRAZ approved these changes

2024-05-09 16:54 UTC, RAJABIBRAZ approved these changes

2024-05-09 16:55 UTC, merged

2024-05-09 16:56 UTC, RAJABIBRAZ reviewed
form is okay