Change of discontinuation date from text to date
palladiumkenya/openmrs-config-kenyaemr pull request #839
Opened 2024-10-15 19:44 UTC by ckote

Changes to also support the pulling of facility list other than inputting text

2024-10-15 20:45 UTC, ojwanganto commented on configuration/ampathforms/MCH-MS_Discontinuation.json
> +							"type": "encounterLocation",
How is this information saved in the database? I know a form can only have one encounter location. @donaldkibet @makombe please help me understand this. Asante

2024-10-16 18:41 UTC, donaldkibet commented on configuration/ampathforms/MCH-MS_Discontinuation.json
> +							"type": "encounterLocation",
We should be using the remote-select here and specify the data source to be locations.

2024-10-16 18:42 UTC, donaldkibet requested changes
we should use `remote-select` here and specify `location` as the data source.

2024-10-17 06:46 UTC, ckote commented
HI @donaldkibet do you mean this:

"questionOptions": {
                "rendering": "remote-select",
                "appointmentKey": "location",
                "dataSource": "location"
              }

2024-10-17 06:46 UTC, ckote commented
Without the appointment Key though?

2024-10-21 09:01 UTC, ckote commented
This is done

2024-10-24 10:02 UTC, merged