add unique encounter uuid for diabetic clinic
palladiumkenya/openmrs-config-kenyaemr pull request #872
Opened 2024-10-31 06:59 UTC by ckote

Added metadata for diabetic clinic encounter; form was using consultation encounter type uuid

2024-10-31 17:48 UTC, makombe requested changes

2024-10-31 17:48 UTC, makombe commented on configuration/ampathforms/Diabetic_Clinical_Encounter_Form.json
> +    "encounter": "DIABETICCONSULTATION",
@ckote  this should be the encounter name and the name you provide is `Diabetic Clinic` and **NOT**`DIABETICCONSULTATION`  please refer to https://github.com/palladiumkenya/openmrs-module-kenyaemr/pull/2041. A wrong name here means the form will never get deployed at all. Thanks

2024-11-01 06:29 UTC, ckote commented
@makombe please see the changes

2024-11-05 07:16 UTC, makombe approved these changes

2024-11-05 07:16 UTC, merged