add new form infectious disease
palladiumkenya/openmrs-config-kenyaemr pull request #966
Opened 2024-12-12 08:05 UTC by ckote

2024-12-12 08:14 UTC, makombe requested changes

2024-12-12 08:14 UTC, makombe commented on configuration/ampathforms/Infectious_Disease_Clinic.json
> +    "uuid": "",
We need the form uuid

2024-12-12 12:29 UTC, ckote commented on configuration/ampathforms/Infectious_Disease_Clinic.json
> +    "uuid": "",
I am adding the metadata for it

2025-01-09 17:54 UTC, Murithijoshua commented
@makombe kindly re-review this at your convenience

2025-01-14 06:09 UTC, andrineM approved these changes

2025-01-14 06:52 UTC, Murithijoshua approved these changes

2025-01-14 06:53 UTC, merged